import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  // Ensure asset URLs include the repo subpath when served (e.g. https://username.github.io/Trimly2/)
  base: '/Trimly2/',
  plugins: [react()],
  build: {
    outDir: 'docs',         // write built index.html + assets into docs/
    emptyOutDir: true,
    rollupOptions: {
      output: {
        // deterministic filenames (remove hashes) so we can reference a predictable path.
        // If you prefer hashed filenames (recommended for cache-busting), remove this block
        // and use the index.html generated by Vite after the build.
        entryFileNames: 'assets/index.js',
        chunkFileNames: 'assets/[name].js',
        assetFileNames: 'assets/[name][extname]'
      }
    }
  }
});
